x-app-base: &app-base
  extends:
    file: docker-compose.yml
    service: app

services:
  app_main:
    <<: *app-base
    env_file:
      - .env

  app_extra:
    <<: *app-base
    env_file:
      - .env.extra

  # Добавляйте дополнительные сервисы по аналогии:
  # app_third:
  #   <<: *app-base
  #   env_file:
  #     - .env.third
